'use strict';

module.exports = {};
module.exports.getMetrics = getMetrics;
module.exports.prepareQueries = prepareQueries;
module.exports.outputMetrics = outputMetrics;
var queue = require('d3-queue').queue;
var AWS = module.exports.AWS = require('aws-sdk');

/**
 * Creates parameters for each cloudwatch query given the input from the user.
 *
 * @param {Date} timestamp from when you want the datapoints to be generated
 * @param {Date} timestamp till when you want the datapoints to be generated
 * @param {String} region where the ELB is present
 * @param {String} name of the ELB
 * @returns {Array} array of desired metric parameters
 */

function prepareQueries(startTime, endTime, region, elbname) {
    var desiredMetrics = {'HTTPCode_Backend_2XX': 'Sum', 'HTTPCode_Backend_3XX': 'Sum', 'HTTPCode_Backend_4XX': 'Sum', 'HTTPCode_Backend_5XX': 'Sum', 'RequestCount': 'Sum', 'Latency': 'Average'};
    var desiredMetricsParameters = [];

    for (var i in desiredMetrics) {

        var params = {
            EndTime: new Date(endTime).toISOString(),
            MetricName: i,
            Namespace: 'AWS/ELB',
            Period: 60,
            StartTime: new Date(startTime).toISOString(),
            Statistics: [desiredMetrics[i].toString()],
            Dimensions: [
                {
                    Name: 'LoadBalancerName',
                    Value: elbname
                }
            ]
        };
        desiredMetricsParameters.push({parameter: params, region: region});
    }
    return desiredMetricsParameters;
}

/**
 * Queues requests for each parameter and returns a formatted version of the result
 *
 * @param {Array} parameters generated by prepareQueries
 * @param {String} region where the ELB is present
 * @param {callback}
 * @returns {Array} formatted results received from cloudwatch getMetricStatistics
 */

function outputMetrics(desiredMetricsDimensions, region, callback) {
    var q = queue(6);
    var allMetrics = [];
    desiredMetricsDimensions.forEach(function (i) {
        q.defer(getMetrics, i.parameter, i.region);
    });
    q.awaitAll(function (err, data) {
        if (err) return callback(err);
        else {
            data.forEach(function (i) {
                allMetrics.push({Label: i.Label, Datapoints: i.Datapoints});
            });
            callback(null, allMetrics);
        }
    });
}

/**
 * Makes requests to the cloudwatch api and gets Sum/Average for
 * HTTPCode_Backend_2XX, HTTPCode_Backend_3XX, HTTPCode_Backend_4XX, HTTPCode_Backend_5XX, RequestCount, Latency
 *
 * @param {Object} parameter Objecy for getMetricStatistics
 * @param {String} region where the ELB is present
 * @param {callback}
 * @returns {Object} Datapoints and Labels for the given MetricName in the form of an Object
 */

function getMetrics(params, region, callback) {
    AWS.config.update({region: region});
    var cloudwatch = new AWS.CloudWatch();

    cloudwatch.getMetricStatistics(params, function (err, data) {
        if (err) return callback(err);
        else {
            return callback(null, data);
        }
    });
}
